---
- name: Copying deploy.sh script to server
  copy:
     src: deploy.sh 
     dest: /deploy.sh
     mode: 0777

- name: Execute the Script
  become: true
  command: sh /deploy.sh

- name: restarting tomcat service
  service:
    name: tomcat
    state: restarted

