//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package com.hexaware.ttlh.hkia.flights.ws.dto;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightStatusDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightStatusDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="airlineCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="airlineName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="aircraftType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportGate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportGate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduledDepartureDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="estimatedDepartureDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="actualDepartureDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="scheduledArrivalDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="estimatedArrivalDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="actualArrivalDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightStatusDTO", propOrder = {
    "airlineCode",
    "airlineName",
    "flightNumber",
    "aircraftType",
    "flightStatus",
    "departureAirportCode",
    "departureAirportName",
    "arrivalAirportCode",
    "arrivalAirportName",
    "departureAirportGate",
    "arrivalAirportGate",
    "scheduledDepartureDateTime",
    "estimatedDepartureDateTime",
    "actualDepartureDateTime",
    "scheduledArrivalDateTime",
    "estimatedArrivalDateTime",
    "actualArrivalDateTime"
})
public class FlightStatusDTO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String airlineCode;
    protected String airlineName;
    protected String flightNumber;
    protected String aircraftType;
    protected String flightStatus;
    protected String departureAirportCode;
    protected String departureAirportName;
    protected String arrivalAirportCode;
    protected String arrivalAirportName;
    protected String departureAirportGate;
    protected String arrivalAirportGate;
    protected DateTimeDTO scheduledDepartureDateTime;
    protected DateTimeDTO estimatedDepartureDateTime;
    protected DateTimeDTO actualDepartureDateTime;
    protected DateTimeDTO scheduledArrivalDateTime;
    protected DateTimeDTO estimatedArrivalDateTime;
    protected DateTimeDTO actualArrivalDateTime;

    /**
     * Gets the value of the airlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * Sets the value of the airlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }

    /**
     * Gets the value of the airlineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineName() {
        return airlineName;
    }

    /**
     * Sets the value of the airlineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineName(String value) {
        this.airlineName = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the aircraftType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftType() {
        return aircraftType;
    }

    /**
     * Sets the value of the aircraftType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftType(String value) {
        this.aircraftType = value;
    }

    /**
     * Gets the value of the flightStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightStatus() {
        return flightStatus;
    }

    /**
     * Sets the value of the flightStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightStatus(String value) {
        this.flightStatus = value;
    }

    /**
     * Gets the value of the departureAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportCode() {
        return departureAirportCode;
    }

    /**
     * Sets the value of the departureAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportCode(String value) {
        this.departureAirportCode = value;
    }

    /**
     * Gets the value of the departureAirportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportName() {
        return departureAirportName;
    }

    /**
     * Sets the value of the departureAirportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportName(String value) {
        this.departureAirportName = value;
    }

    /**
     * Gets the value of the arrivalAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportCode() {
        return arrivalAirportCode;
    }

    /**
     * Sets the value of the arrivalAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportCode(String value) {
        this.arrivalAirportCode = value;
    }

    /**
     * Gets the value of the arrivalAirportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportName() {
        return arrivalAirportName;
    }

    /**
     * Sets the value of the arrivalAirportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportName(String value) {
        this.arrivalAirportName = value;
    }

    /**
     * Gets the value of the departureAirportGate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportGate() {
        return departureAirportGate;
    }

    /**
     * Sets the value of the departureAirportGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportGate(String value) {
        this.departureAirportGate = value;
    }

    /**
     * Gets the value of the arrivalAirportGate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportGate() {
        return arrivalAirportGate;
    }

    /**
     * Sets the value of the arrivalAirportGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportGate(String value) {
        this.arrivalAirportGate = value;
    }

    /**
     * Gets the value of the scheduledDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getScheduledDepartureDateTime() {
        return scheduledDepartureDateTime;
    }

    /**
     * Sets the value of the scheduledDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setScheduledDepartureDateTime(DateTimeDTO value) {
        this.scheduledDepartureDateTime = value;
    }

    /**
     * Gets the value of the estimatedDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getEstimatedDepartureDateTime() {
        return estimatedDepartureDateTime;
    }

    /**
     * Sets the value of the estimatedDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setEstimatedDepartureDateTime(DateTimeDTO value) {
        this.estimatedDepartureDateTime = value;
    }

    /**
     * Gets the value of the actualDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getActualDepartureDateTime() {
        return actualDepartureDateTime;
    }

    /**
     * Sets the value of the actualDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setActualDepartureDateTime(DateTimeDTO value) {
        this.actualDepartureDateTime = value;
    }

    /**
     * Gets the value of the scheduledArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getScheduledArrivalDateTime() {
        return scheduledArrivalDateTime;
    }

    /**
     * Sets the value of the scheduledArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setScheduledArrivalDateTime(DateTimeDTO value) {
        this.scheduledArrivalDateTime = value;
    }

    /**
     * Gets the value of the estimatedArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getEstimatedArrivalDateTime() {
        return estimatedArrivalDateTime;
    }

    /**
     * Sets the value of the estimatedArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setEstimatedArrivalDateTime(DateTimeDTO value) {
        this.estimatedArrivalDateTime = value;
    }

    /**
     * Gets the value of the actualArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getActualArrivalDateTime() {
        return actualArrivalDateTime;
    }

    /**
     * Sets the value of the actualArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setActualArrivalDateTime(DateTimeDTO value) {
        this.actualArrivalDateTime = value;
    }

}
