---

- name: Creating a Directory for Source code.
  command: mkdir deployapp
 
- name: Changing the Directory
  command: cd deployapp

- name: Cloning Git Repository
  git:
     repo: https://ansible-story@dev.azure.com/ansible-story/springbootapp_mumbai/_git/springbootapp_mumbai
     dest: /home/ubuntu/deployapp
     version: master

- name: Changing to source Code Repo
  command: cd  /home/ubuntu/deployapp/springbootapp_mumbai/FlightStatusServiceImpl/

- name: Maven clean and Package
  command: mvn clean package

- name: Copying the jar file to tomcat server.
  command: cp  /home/ubuntu/deployapp/springbootapp_mumbai/FlightStatusServiceImpl/target/FlightStatusServiceImpl-0.1.0.jar /usr/share/tomcat/webapps/
 
- name: maven run the app server
  command:  mvn spring-boot:run -Doracle.jdbc.timezoneAsRegion=false

