//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package com.hexaware.ttlh.hkia.flights.ws.request;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hexaware.ttlh.hkia.flights.ws.common.Request;
import com.hexaware.ttlh.hkia.flights.ws.dto.DateTimeDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://ttlh.hexaware.com/hkia/flights/ws/common}Request">
 *       &lt;sequence>
 *         &lt;element name="airlineCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="departureAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="arrivalAirportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scheduledDepartureDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *         &lt;element name="scheduledArrivalDateTime" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}DateTimeDTO" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "airlineCode",
    "flightNumber",
    "departureAirportCode",
    "arrivalAirportCode",
    "scheduledDepartureDateTime",
    "scheduledArrivalDateTime"
})
@XmlRootElement(name = "FlightStatusRequest", namespace = "http://ttlh.hexaware.com/hkia/flights/ws/request")
public class FlightStatusRequest
    extends Request
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String airlineCode;
    protected String flightNumber;
    protected String departureAirportCode;
    protected String arrivalAirportCode;
    protected DateTimeDTO scheduledDepartureDateTime;
    protected DateTimeDTO scheduledArrivalDateTime;

    /**
     * Gets the value of the airlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * Sets the value of the airlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the departureAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirportCode() {
        return departureAirportCode;
    }

    /**
     * Sets the value of the departureAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirportCode(String value) {
        this.departureAirportCode = value;
    }

    /**
     * Gets the value of the arrivalAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirportCode() {
        return arrivalAirportCode;
    }

    /**
     * Sets the value of the arrivalAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirportCode(String value) {
        this.arrivalAirportCode = value;
    }

    /**
     * Gets the value of the scheduledDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getScheduledDepartureDateTime() {
        return scheduledDepartureDateTime;
    }

    /**
     * Sets the value of the scheduledDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setScheduledDepartureDateTime(DateTimeDTO value) {
        this.scheduledDepartureDateTime = value;
    }

    /**
     * Gets the value of the scheduledArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeDTO }
     *     
     */
    public DateTimeDTO getScheduledArrivalDateTime() {
        return scheduledArrivalDateTime;
    }

    /**
     * Sets the value of the scheduledArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeDTO }
     *     
     */
    public void setScheduledArrivalDateTime(DateTimeDTO value) {
        this.scheduledArrivalDateTime = value;
    }

}
