//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package com.hexaware.ttlh.hkia.flights.ws.response;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.hexaware.ttlh.hkia.flights.ws.common.Response;
import com.hexaware.ttlh.hkia.flights.ws.dto.FlightStatusDTO;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://ttlh.hexaware.com/hkia/flights/ws/common}Response">
 *       &lt;sequence>
 *         &lt;element name="flightStatus" type="{http://ttlh.hexaware.com/hkia/flights/ws/dto}FlightStatusDTO" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightStatus"
})
@XmlRootElement(name = "FlightStatusResponse", namespace = "http://ttlh.hexaware.com/hkia/flights/ws/response")
public class FlightStatusResponse
    extends Response
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<FlightStatusDTO> flightStatus;

    /**
     * Gets the value of the flightStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * {@link FlightStatusDTO }
     * 
     * 
     */
    public List<FlightStatusDTO> getFlightStatus() {
        if (flightStatus == null) {
            flightStatus = new ArrayList<FlightStatusDTO>();
        }
        return this.flightStatus;
    }

}
