//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package com.hexaware.ttlh.hkia.flights.ws.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hexaware.ttlh.hkia.flights.ws.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hexaware.ttlh.hkia.flights.ws.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightStatusResponse }
     * 
     */
    public FlightStatusResponse createFlightStatusResponse() {
        return new FlightStatusResponse();
    }

}
