//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package com.hexaware.ttlh.hkia.flights.ws.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.hexaware.ttlh.hkia.flights.ws.response.FlightStatusResponse;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Error" type="{http://ttlh.hexaware.com/hkia/flights/ws/common}FlightStatusError"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "error"
})
@XmlSeeAlso({
    FlightStatusResponse.class
})
public class Response
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Error", required = true)
    protected FlightStatusError error;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link FlightStatusError }
     *     
     */
    public FlightStatusError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightStatusError }
     *     
     */
    public void setError(FlightStatusError value) {
        this.error = value;
    }

}
